FROM kalilinux/kali-rolling

WORKDIR /root 

RUN apt -y update --fix-missing && apt -y upgrade && apt -y autoremove && apt clean \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y iproute2 inetutils-ping curl host mtr-tiny tcpdump iptables traceroute ssh postgresql \ 
    && rm -rf /var/lib/apt/lists/*

