name: Hadolint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 15 * * 4'

permissions:
  contents: read

jobs:
  hadolint:
    name: Run Hadolint on all Dockerfiles
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint dhcp-server DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/dhcp-server/DOCKERFILE
          format: sarif
          output-file: hadolint-dhcp-server.sarif
          no-fail: true

      - name: Upload dhcp-server SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-dhcp-server.sarif
          category: dhcp-server
          wait-for-processing: true

      - name: Lint dmz-router-external DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/dmz-router-external/DOCKERFILE
          format: sarif
          output-file: hadolint-dmz-router-external.sarif
          no-fail: true

      - name: Upload dmz-router-external SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-dmz-router-external.sarif
          category: dmz-router-external
          wait-for-processing: true

      - name: Lint dmz-router-internal DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/dmz-router-internal/DOCKERFILE
          format: sarif
          output-file: hadolint-dmz-router-internal.sarif
          no-fail: true

      - name: Upload dmz-router-internal SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-dmz-router-internal.sarif
          category: dmz-router-internal
          wait-for-processing: true

      - name: Lint dns-server DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/dns-server/DOCKERFILE
          format: sarif
          output-file: hadolint-dns-server.sarif
          no-fail: true

      - name: Upload dns-server SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-dns-server.sarif
          category: dns-server
          wait-for-processing: true

      - name: Lint eve DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/eve/DOCKERFILE
          format: sarif
          output-file: hadolint-eve.sarif
          no-fail: true

      - name: Upload eve SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-eve.sarif
          category: eve
          wait-for-processing: true

      - name: Lint http-server DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/http-server/DOCKERFILE
          format: sarif
          output-file: hadolint-http-server.sarif
          no-fail: true

      - name: Upload http-server SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-http-server.sarif
          category: http-server
          wait-for-processing: true

      - name: Lint pc1 DOCKERFILE
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./source/DockerFiles/pc1/DOCKERFILE
          format: sarif
          output-file: hadolint-pc1.sarif
          no-fail: true

      - name: Upload pc1 SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-pc1.sarif
          category: pc1
          wait-for-processing: true
